/** @type {import('next').NextConfig} */
const withPWA = require("next-pwa")({
  dest: "public",
  register: true,
  skipWaiting: true,
  disable: process.env.NODE_ENV === "development",
});

const nextConfig = {
  reactStrictMode: true,
  images: {
    domains: [
      "user-images.githubusercontent.com",
      "media.newstrack.in",
      "www.themoviedb.org",
      "preview.redd.it",
      "www.uptvs.com",
      "ntvb.tmsimg.com",
      "www.hindustantimes.com",
      "movies.universalpictures.com",
      "www.thestatesman.com",
      "images.thedirect.com",
      "images.fandango.com",
      "www.megmovie.net",
      "filmr.ir",
      "lumiere-a.akamaihd.net",
      "4kwallpapers.com",
      "encrypted-tbn0.gstatic.com",
      "images.squarespace-cdn.com",
      "images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com",
      "i.redd.it",
      "www.slashfilm.com",
      "c4.wallpaperflare.com",
      "images3.alphacoders.com",
      "images.hdqwalls.com",
      "i.pinimg.com",
      "bloody-disgusting.com",
      "w0.peakpx.com",
      "wallpapercave.com",
      "wallpaperaccess.com",
      "www.rollingstone.com",
      "gizmodo.com.au",
      "www.pixground.com",
      "cdn.mos.cms.futurecdn.net",
      "e0.pxfuel.com",
      "wallpapercrafter.com",
      "m.media-amazon.com",
      "wallpapercosmos.com",
      "funmauj.b-cdn.net",
      "wallpapers.com",
      "www.enwallpaper.com",
      "is.zobj.net",
      "cdn.wallpapersafari.com",
      "cutewallpaper.org",
      "wallpapersmug.com",
      "alitaexperience.com",
      "staticg.sportskeeda.com",
      "r1.ilikewallpaper.net",
      "image.winudf.com",
      "img.freepik.com",
      "papers.co",
      "cdn.vox-cdn.com",
    ],
    remotePatterns: [
      {
        protocol: "https",
        hostname: "www.uptvs.com",
        port: "",
        pathname: "/account123/**",
      },
    ],
  },
};

module.exports = nextConfig;
